# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpVault < Formula
  desc "Cache op:// secrets in macOS Keychain"
  homepage "https://github.com/sunakan/op-vault"
  version "0.3.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/sunakan/op-vault/releases/download/v0.3.1/op-vault_darwin_arm64.tar.gz"
    sha256 "ac2dd68bee4b9f0b5c2d45a57c1244b2fa0adb4582df83dbf9169234682fb7d4"

    define_method(:install) do
      bin.install "op-vault"
    end
  end

  test do
    system "#{bin}/op-vault", "version"
  end
end
