# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpVault < Formula
  desc "Cache op:// secrets in macOS Keychain"
  homepage "https://github.com/sunakan/op-vault"
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/sunakan/op-vault/releases/download/v0.3.0/op-vault_darwin_arm64.tar.gz"
    sha256 "b605ccc858f105673269efbe9839fbf07d056b124ab6796f2ce56090e6429e4b"

    define_method(:install) do
      bin.install "op-vault"
    end
  end

  test do
    system "#{bin}/op-vault", "version"
  end
end
