# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpVault < Formula
  desc "Cache op:// secrets in macOS Keychain"
  homepage "https://github.com/sunakan/op-vault"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/sunakan/op-vault/releases/download/v0.1.0/op-vault_darwin_arm64.tar.gz"
    sha256 "04e00571286b8609e359787a96f957160bd97c74253d9b86c0848d4bef540f32"

    define_method(:install) do
      bin.install "op-vault"
    end
  end

  test do
    system "#{bin}/op-vault", "version"
  end
end
